plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'own.retrogamewatchface'
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId "own.retrogamewatchface"
        minSdk 33
        targetSdk 37
        versionCode 1
        versionName "1.0"

    }

    buildTypes {
        release {
            optimization {
                enable false
            }
        }
    }
    enableKotlin false
}

dependencies {
}