package own.retrogamewatch;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class drawable {
        public static final int preview = 0x7f010000;
        public static final int preview_circular = 0x7f010001;
        public static final int wfs_0_61490fe4_8773_45d9_9e81_8390316ee3f4 = 0x7f010002;
        public static final int wfs_100_aa384422_da58_4370_a599_4af6512c3072 = 0x7f010003;
        public static final int wfs_10_4a85608a_bde1_4bf0_b84f_d87bea8f643a = 0x7f010004;
        public static final int wfs_20_6abcab5f_0805_4342_a3bb_c861d28e8990 = 0x7f010005;
        public static final int wfs_30_3e98648b_7c3f_4a13_b6e4_bb6a6711cc7b = 0x7f010006;
        public static final int wfs_40_a1a09d8a_62cc_428e_98ff_71d87bd0eaf6 = 0x7f010007;
        public static final int wfs_50_09c7f318_a9c0_4e2c_9f31_88d227e96de5 = 0x7f010008;
        public static final int wfs_60_4c6bbf95_2b59_4cb8_b737_ac946353cba7 = 0x7f010009;
        public static final int wfs_70_81d63fa6_0539_42dd_a66b_43e57a2b30a8 = 0x7f01000a;
        public static final int wfs_80_99f1bb9c_bbaa_4684_989a_c375d6758d92 = 0x7f01000b;
        public static final int wfs_90_22f640e4_a2fb_4f7b_9f21_d65a74c5cf57 = 0x7f01000c;
        public static final int wfs_clear_9d1805d5_83e6_4906_82c0_160d5a766096 = 0x7f01000d;
        public static final int wfs_cloudy_33c6d5c5_8654_41cc_a267_df06c4af55b7 = 0x7f01000e;
        public static final int wfs_rainy_feb31136_bf4f_4b76_99f7_1507907b7b97 = 0x7f01000f;
        public static final int wfs_snowy_ac572c3e_296c_4f37_b74f_1a66c311f420 = 0x7f010010;
    }

    public static final class font {
        public static final int wfs_pixel_f3ff58bb_f555_4438_bce1_9765d6d7be2d = 0x7f020000;
    }

    public static final class raw {
        public static final int watchface = 0x7f030000;
    }

    public static final class string {
        public static final int ID_LABEL_RETRO_GAME_WATCH = 0x7f040000;
        public static final int app_name = 0x7f040001;
        public static final int title_runtime = 0x7f040002;
        public static final int watchface_title = 0x7f040003;
    }

    public static final class xml {
        public static final int watch_face = 0x7f050000;
        public static final int watch_face_info = 0x7f050001;
        public static final int watch_face_shapes = 0x7f050002;
        public static final int splits0 = 0x7f050003;
    }
}
